import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import { ThemeProvider } from "next-themes";

const raleway = Raleway({
  variable: "--font-releway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${raleway.variable} antialiased`}>
        <ThemeProvider attribute="class">
          <Theme
            accentColor="blue"
            grayColor="gray"
            panelBackground="solid"
            scaling="110%"
            radius="large"
          >
            {children}
            <ThemePanel />
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
